const { generateOvertonesArrays } = require('./overtoneGen.js');

// Generate a perfect harmonic series
const perfectHarmonicSeries = generateOvertonesArrays(
    1.0,  // harmonicPurity: Perfect harmonics
    0.5,  // spectralBalance: Balanced
    0.5,  // oddEvenBias: Balanced
    0.0,  // formantStrength: None
    0.7,  // spectralRichness: Rich
    0.0,  // irregularity: None
    10    // maxHarmonics (e.g., 10 partials)
);

console.log('\n--- Perfect Harmonic Series Generated by overtoneGen.js ---');
console.log('Partial | Ratio');
console.log('-------------------');

perfectHarmonicSeries.ratios.forEach((ratio, index) => {
    console.log(`${String(index + 1).padEnd(7)} | ${ratio.toFixed(4)}`);
});
console.log('-------------------');
